# Generated by Django 3.1.7 on 2021-06-19 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='食譜recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='食材ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('調味料sauce', models.CharField(max_length=10)),
                ('食譜recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.食譜recipe')),
            ],
        ),
    ]
