# Generated by Django 3.1.7 on 2021-06-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_食材ingredient_食譜recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='食材ingredient',
        ),
        migrations.DeleteModel(
            name='食譜recipe',
        ),
    ]
