# Generated by Django 3.1.7 on 2021-06-19 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20210619_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='食材',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('g', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='食譜',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('食材', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.食材')),
            ],
        ),
    ]
