# Generated by Django 3.1.7 on 2021-06-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_食材_食譜'),
    ]

    operations = [
        migrations.AddField(
            model_name='食譜',
            name='g',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
